--<DS_SCRIPT>
-- DESCRIÇÃO..: Cria a tabela TISS_GUIA_REAPRESENTACAO para controlar as reapresentações das GUIAS
-- RESPONSAVEL: Saulo Rocha
-- DATA.......: 26/06/2017
-- APLICAÇÃO..: FFCV
--</DS_SCRIPT>
--<USUARIO=DBAMV>
CREATE TABLE DBAMV.TISS_GUIA_REAPRESENTACAO
  ( ID               NUMBER NOT NULL
  , ID_PAI           NUMBER NOT NULL
  , SN_REJEITADA     VARCHAR2(1) DEFAULT 'N' NOT NULL
  , SN_REAPRESENTADA VARCHAR2(1) DEFAULT 'N' NOT NULL
  , CD_GLOSA_TUSS              VARCHAR2(10)   NULL
  , DT_DEVOLUCAO               DATE           NULL )
  TABLESPACE MV2000_D
/
COMMENT ON TABLE DBAMV.TISS_GUIA_REAPRESENTACAO IS 'Controla as reapresentações das guias TISS'
/
COMMENT ON COLUMN DBAMV.TISS_GUIA_REAPRESENTACAO.ID IS 'Identificação da TISS_GUIA (FK)'
/
COMMENT ON COLUMN DBAMV.TISS_GUIA_REAPRESENTACAO.ID_PAI IS 'Identificação da TISS_LOTE (FK)'
/
COMMENT ON COLUMN DBAMV.TISS_GUIA_REAPRESENTACAO.SN_REJEITADA IS 'Sinaliza se a guia foi devolvida'
/
COMMENT ON COLUMN DBAMV.TISS_GUIA_REAPRESENTACAO.SN_REAPRESENTADA IS 'Sinaliza se a guia foi reapresentada'
/
COMMENT ON COLUMN DBAMV.TISS_GUIA_REAPRESENTACAO.CD_GLOSA_TUSS IS 'Código do motivo de glosa TUSS (tab38) de devolução do convênio'
/
COMMENT ON COLUMN DBAMV.TISS_GUIA_REAPRESENTACAO.DT_DEVOLUCAO IS 'Data de devolução do convênio'
/
ALTER TABLE DBAMV.TISS_GUIA_REAPRESENTACAO
  ADD CONSTRAINT CNT_TISS_GUIA_REAPRESENCAO_PK PRIMARY KEY ( ID , ID_PAI )
  USING INDEX TABLESPACE MV2000_I
/
ALTER TABLE DBAMV.TISS_GUIA_REAPRESENTACAO
  ADD CONSTRAINT CNT_TISS_GUIA_LT_TISS_LOTE_FK FOREIGN KEY ( ID_PAI ) REFERENCES DBAMV.TISS_LOTE ( ID )
/
ALTER TABLE DBAMV.TISS_GUIA_REAPRESENTACAO
  ADD CONSTRAINT CNT_TISS_GUIA_RP_TISS_GUIA_FK FOREIGN KEY ( ID ) REFERENCES DBAMV.TISS_GUIA ( ID )
/
CREATE INDEX DBAMV.IND_TISS_GUIA_LT_TISS_GUIA_FK
  ON DBAMV.TISS_GUIA_REAPRESENTACAO ( ID_PAI ) TABLESPACE MV2000_I
/
CREATE INDEX DBAMV.IND_TISS_GUIA_RP_TISS_GUIA_FK
  ON DBAMV.TISS_GUIA_REAPRESENTACAO ( ID ) TABLESPACE MV2000_I
/
GRANT DELETE,INSERT,SELECT,UPDATE ON DBAMV.TISS_GUIA_REAPRESENTACAO TO MV2000
/
CREATE OR REPLACE PUBLIC SYNONYM TISS_GUIA_REAPRESENTACAO FOR DBAMV.TISS_GUIA_REAPRESENTACAO
/